language: node_js
sudo: false
node_js:
    - '6.6.0'
addons:
  apt:
    sources:
    # Needed to install g++ that is used by npms's native modules
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
matrix:
    fast_finish: true
    allow_failures:
        - node_js: 5.12.0
before_script:
    - npm install -g gulp-cli node-gyp
    - mysql -u root -e "CREATE USER 'chat_app'@'localhost' IDENTIFIED BY 'lets_talk'"
    - mysql -u root -e "CREATE DATABASE IF NOT EXISTS chat_app";
    - mysql -u root -e "GRANT ALL PRIVILEGES ON chat_app.* TO 'chat_app'@'localhost';"
    - mysql -u root chat_app -e "CREATE TABLE IF NOT EXISTS user_info ( user_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, username VARCHAR(30) NOT NULL UNIQUE, password CHAR(128) NOT NULL, email VARCHAR(50) NOT NULL UNIQUE, last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP, session CHAR(36) );"
    - mysql -u root chat_app -e "CREATE TABLE IF NOT EXISTS messages ( id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, sender_id VARCHAR(30) NOT NULL, message TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL, message_time TIMESTAMP NOT NULL, FOREIGN KEY (sender_id) REFERENCES user_info(username) ON DELETE CASCADE );"
    - mysql -u root chat_app -e "CREATE INDEX messages_time_index USING BTREE ON messages(message_time DESC);"
services:
    - mysql
env:
    - TRAVIS=travis CXX=g++-4.8
