language: node_js
sudo: false
node_js:
    - '6.6.0'
addons:
  apt:
    sources:
    # Needed to install g++ that is used by npms's native modules
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
matrix:
    fast_finish: true
    allow_failures:
        - node_js: 5.12.0
before_script:
    - npm install -g gulp-cli node-gyp
    - mysql -u root < ./db-schema-setup.sql
services:
    - mysql
env:
    - TRAVIS=travis CXX=g++-4.8
