
language: node_js
node_js:
    - 6.6.0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
matrix:
    fast_finish: true
    allow_failures:
        - node_js: 5.12.0
before_install:
    - npm install -g npm
before_script:
    - npm install -g gulp-cli node-gyp
    - bower install
services:
    - mysql
env:
  - TRAVIS=travis CXX=g++-4.8
